CMake: explicitly depend on Qt6::SvgWidgets
rpcs3/rpcs3qt/welcome_dialog.cpp:8:10: fatal error: 'QSvgWidget' file not found
 #include <QSvgWidget>
          ^~~~~~~~~~~~